version: "3.9"

services:
  frontend:
    build: ./front-end
    ports:
      - "3000:80"  # Expose Nginx on port 3000

  backend:
    build: ./back-end
    ports:
      - "5001:5001"
    env_file:
      - ./back-end/.env
